export const TEST_IDS = {
  auth: {
    dashboard: 'auth.dashboard',
    emailInput: 'auth.email-input',
    loginTab: 'auth.login-tab',
    logoutButton: 'auth.logout-button',
    nameInput: 'auth.name-input',
    openAuthButton: 'auth.open-auth-button',
    passwordInput: 'auth.password-input',
    registerTab: 'auth.register-tab',
    submitButton: 'auth.submit-button',
    userEmail: 'auth.user-email',
  },
  catalog: {
    cityInput: 'catalog.city-input',
    createOrderButton: 'catalog.create-order-button',
    endDateInput: 'catalog.end-date-input',
    firstBicycleSelect: 'catalog.first-bicycle-select',
    maxPriceInput: 'catalog.max-price-input',
    minPriceInput: 'catalog.min-price-input',
    screen: 'catalog.screen',
    sizeL: 'catalog.size-l',
    sizeM: 'catalog.size-m',
    sizeS: 'catalog.size-s',
    startDateInput: 'catalog.start-date-input',
  },
  orderDetail: {
    cancelButton: 'order-detail.cancel-button',
    cancelCommentInput: 'order-detail.cancel-comment-input',
    payDepositButton: 'order-detail.pay-deposit-button',
    payRentButton: 'order-detail.pay-rent-button',
    screen: 'order-detail.screen',
  },
  orderRequest: {
    contactNameInput: 'order-request.contact-name-input',
    contactPhoneInput: 'order-request.contact-phone-input',
    createButton: 'order-request.create-button',
    deliveryAddressInput: 'order-request.delivery-address-input',
    endDateInput: 'order-request.end-date-input',
    safetyCheckbox: 'order-request.safety-checkbox',
    screen: 'order-request.screen',
    startDateInput: 'order-request.start-date-input',
    userCommentInput: 'order-request.user-comment-input',
  },
  navigation: {
    backButton: 'navigation.back-button',
  },
  orders: {
    screen: 'orders.screen',
  },
  profile: {
    screen: 'profile.screen',
  },
  tabs: {
    catalog: 'tabs.catalog',
    orders: 'tabs.orders',
    profile: 'tabs.profile',
  },
} as const;
